### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/cssi-prework-python-variable-types-readme#1]
In the intro-  "In Python, there are a few different variable types we'll be going over. Note that here "type" does not mean "data type". Unlike in languages such as C, C++, and Objective-C, data types in Python do not need to be explicitly declared when variables are assigned."-  do you think this might confuse students more than help them out? Can we just jump right into local and global variables here and just introduce those two things by, for example, presenting a problem whose answer is "by using local and global variables". For example, something like "What if we have situations where we want only one part of our program to have access to the variables in a function" or "What if we want different parts of our program to have access to the variables in a function. Is there an easy way to do that?"

Also in the situation where you should use global variables sparingly, is it possible to include a real world example of that to drive the point home?

**Comment by dfenjves** [comment]
Fixed - can't find much on global variable use in python, but updated intro
